### ISSUE TITLE
Add Foreign Key not working properly

### ISSUE THREAD

**Issue by fishyBenjy01** [blingo77/PostPie#1]
## Add Foreign Key not working properly
The add_foreign_key function is not adding a fk to a table properly

**Comment by blingo77** [comment]
## Fix
If you are running into this problem make sure:

- The table that you want to add the Foreign Key to already has the column that will hold the FK.
- Make sure that the name of the Foreign Key you want to add is the same name of the column name that will hold the FK.
- You can create a table that has the FK column name or add to an existing table.

If the problem still happens after just let me know and I will take a look further into it.

**Comment by blingo77** [comment]
## Fix
If you are running into this problem make sure:

- The table that you want to add the Foreign Key to already has the column that will hold the FK.
- Make sure that the name of the Foreign Key you want to add is the same name of the column name that will hold the FK.
- You can create a table that has the FK column name or add to an existing table.

If the problem still happens after just let me know and I will take a look further into it.
