### ISSUE TITLE
show_table Issue

### ISSUE THREAD

**Issue by Lengend97** [blingo77/PostPie#2]
# show_table Issue
### Issue
When I use the show_table function im trying to use the table information in a program, but when I try to assign a variable to the table info, it won't work and will show up as `None` . 

### Code
``` 
data = ex.show_table('orders')
print(data)

Output:
None
```

**Comment by blingo77** [comment]
# Fix
Currently, the show_table function only prints table information to the terminal. The next release how ever will have the function return a tuple of the rows from the table. The next release should be coming in the following weeks.
